### ISSUE TITLE
wis2box-container exits after 'python3 wis2box-ctl.py start'

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#245]
On the demo-wis2box, the wis2box-containers exists after restarting the stack stop/start command implemented in wis2box-ctl.py

See error-log below. The issue appears to that the wis2box-api container is not ready yet for connections. 
```
Adding to API configuration
[2022-09-02T13:21:34Z] {/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:812} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7d033795b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /oapi/admin/resources/messages
[2022-09-02T13:21:36Z] {/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:812} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7d033794f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /oapi/admin/resources/messages
[2022-09-02T13:21:40Z] {/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:812} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7d03379070>: Failed to establish a new connection: [Errno 111] Connection refused')': /oapi/admin/resources/messages
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f7d03379220>: Failed to establish a new connection: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='wis2box-api', port=80): Max retries exceeded with url: /oapi/admin/resources/messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7d03379220>: Failed to establish a new connection: [Errno 111] Connection refused'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/wis2box", line 33, in <module>
    sys.exit(load_entry_point('wis2box==0.4.dev0', 'console_scripts', 'wis2box')())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/wis2box-0.4.dev0-py3.9.egg/wis2box/api/__init__.py", line 101, in setup
    api_config.add_collection('messages', collection)
  File "/usr/local/lib/python3.9/site-packages/wis2box-0.4.dev0-py3.9.egg/wis2box/api/config/pygeoapi.py", line 65, in add_collection
    if self.has_collection(name):
  File "/usr/local/lib/python3.9/site-packages/wis2box-0.4.dev0-py3.9.egg/wis2box/api/config/pygeoapi.py", line 95, in has_collection
    r = self.http.get(f'{self.url}/{name}')
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='wis2box-api', port=80): Max retries exceeded with url: /oapi/admin/resources/messages (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7d03379220>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

After repeating the start-command  the wis2box-container starts successfully.

**Comment by maaikelimper** [comment]
I haven't seen this error anymore, closing
