### ISSUE TITLE
improve exception handling for transformation errors

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#370]
For example template mismatch would produce the following output in the logs:
```
[2023-01-24T10:00:00Z] {/usr/local/lib/python3.9/site-packages/csv2bufr/__init__.py:90} ERROR - Column SlrJ24 not found in input data
[2023-01-24T10:00:00Z] {/usr/local/lib/python3.9/site-packages/wis2box-1.0b1-py3.9.egg/wis2box/handler.py:109} ERROR - Failed to transform file http://minio:9000/wis2box-incoming/mwi/malawi_wmo_demo/data/core/weather/surface-based-observations/synop/WIGOS_0-454-2-AWSMULANJE_2023-01-24T0155.csv :
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/wis2box-1.0b1-py3.9.egg/wis2box/handler.py", line 101, in handle
    plugin.transform(
  File "/usr/local/lib/python3.9/site-packages/wis2box-1.0b1-py3.9.egg/wis2box/data/csv2bufr.py", line 78, in transform
    for item in results:
  File "/usr/local/lib/python3.9/site-packages/csv2bufr/__init__.py", line 703, in transform
    message.parse(data_dict, mappings)
  File "/usr/local/lib/python3.9/site-packages/csv2bufr/__init__.py", line 515, in parse
    value = get_(eccodes_key, mappings[section], data)
  File "/usr/local/lib/python3.9/site-packages/csv2bufr/__init__.py", line 114, in get_
    value = parse_value(element['value'], data)
  File "/usr/local/lib/python3.9/site-packages/csv2bufr/__init__.py", line 91, in parse_value
    raise ValueError
ValueError
```

Which basically means :
```
[2023-01-24T10:00:00Z] {/usr/local/lib/python3.9/site-packages/wis2box-1.0b1-py3.9.egg/wis2box/handler.py:109} ERROR - Failed to transform file http://minio:9000/wis2box-incoming/mwi/malawi_wmo_demo/data/core/weather/surface-based-observations/synop/WIGOS_0-454-2-AWSMULANJE_2023-01-24T0155.csv : csv does not match provided template
```

wis2box/handler.py catches the error from the plugin: 
```
try:
                if self.is_http:
                    plugin.transform(
                        get_data(self.filepath),
                        filename=self.filepath.split('/')[-1],
                    )
                else:
                    plugin.transform(self.filepath)
            except Exception as err:
                msg = f'Failed to transform file {self.filepath} : {err}'
                LOGGER.error(msg, exc_info=True)
                self.publish_failure_message(
                    description="failed to transform file",
                    plugin=plugin)
                return False
```

Could we define a custom Exception-class for the plugins to pass information about the error to the handler ? 

A custom exception would allow the plugin to report the wigos-id in addition to the error-message, so we can collect metrics per station and inform the user to know which station is causing the issue

**Comment by tomkralidis** [comment]
- make generic the looping of transform results to as an abstraction in `wis2box.data.base`
  - can be observations or not
- define a list of status code for external packages (like csv2bufr, synop2bufr) to implement
  - add to plugin development documentation

cc @david-i-berry @RoryPTB

**Comment by tomkralidis** [comment]
Closing; related to #329
