### ISSUE TITLE
fix BUFR pipeline when data has no year or month derivations

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2box#415]
```
2023-03-11 10:25:10 [2023-03-11T15:25:10Z] {/usr/local/lib/python3.8/dist-packages/wis2box-1.0b1-py3.8.egg/wis2box/data/bufr4.py:171} ERROR - unsupported format string passed to NoneType.__format__
2023-03-11 10:25:10 Traceback (most recent call last):
2023-03-11 10:25:10   File "/usr/local/lib/python3.8/dist-packages/wis2box-1.0b1-py3.8.egg/wis2box/data/bufr4.py", line 169, in transform_subset
2023-03-11 10:25:10     data_date = parser.get_time()
2023-03-11 10:25:10   File "/usr/local/lib/python3.8/dist-packages/bufr2geojson/__init__.py", line 343, in get_time
2023-03-11 10:25:10     time_ = f"{year:04d}-{month:02d}-{day:02d} {hour:02d}:{minute:02d}:{second:02d}"  # noqa
2023-03-11 10:25:10 TypeError: unsupported format string passed to NoneType.__format__
```

Issue raised at: https://github.com/wmo-im/bufr2geojson/blob/main/bufr2geojson/__init__.py#L340

Local debugging:
```
DEBUG - year=None, month=None, day=1, hour=0, minute=0, second=0
```

To reproduce locally against a single file:
```bash
wis2box data ingest --topic-hierarchy ita.roma_met_centre.data.core.weather.surface-based-observations.synop --path $WIS2BOX_DATADIR/observations/italy/A_ISMD02LIIB201200_C_EDZW_20220320120604_11413047.bin
```

**Comment by tomkralidis** [comment]
bufr2geojson update in https://github.com/wmo-im/bufr2geojson/pull/19

**Comment by tomkralidis** [comment]
bufr2geojson additional error handling in https://github.com/wmo-im/bufr2geojson/pull/20
