### ISSUE TITLE
document filename requirements for synop2bufr

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#439]
The synop2bufr plugin in wis2box-management/wis2box/data/synop2bufr.py relies on a specific filename pattern to determine year and month:
```
        file_match = self.validate_filename_pattern(filename)

        ...

        year = int(file_match.group(1))
        month = int(file_match.group(2))
```

And a failure to provide the correct filename-pattern can result in the (not-too-descriptive) error "no such group" 

We need to document filename-requirement for synop2bufr to ensure users know how to correctly provide year and month as input.
Also the logging should be more descriptive to help users ensure they provide the correct filename-format.

**Comment by tomkralidis** [comment]
Here is what is returned when an invalid file format is provided:

```
[2023-05-02T12:24:41Z] {/usr/local/lib/python3.8/dist-packages/wis2box-1.0b2-py3.8.egg/wis2box/data/synop2bufr.py:68} ERROR - Invalid filename format: A_SMRO01YRBK181200_C_EDZW_123.txt (^A_SMR.*EDZW_(\d{4})(\d{2}).*.txt$)
[2023-05-02T12:24:41Z] {/usr/local/lib/python3.8/dist-packages/wis2box-1.0b2-py3.8.egg/wis2box/handler.py:105} ERROR - Failed to transform file http://minio:9000/wis2box-incoming/rou/rnimh/data/core/weather/surface-based-observations/synop/A_SMRO01YRBK181200_C_EDZW_123.txt : Invalid filename format: A_SMRO01YRBK181200_C_EDZW_123.txt (^A_SMR.*EDZW_(\d{4})(\d{2}).*.txt$)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wis2box-1.0b2-py3.8.egg/wis2box/handler.py", line 97, in handle
    plugin.transform(
  File "/usr/local/lib/python3.8/dist-packages/wis2box-1.0b2-py3.8.egg/wis2box/data/synop2bufr.py", line 69, in transform
    raise ValueError(msg)
ValueError: Invalid filename format: A_SMRO01YRBK181200_C_EDZW_123.txt (^A_SMR.*EDZW_(\d{4})(\d{2}).*.txt$)
```

Documentation on the plugin and requirements for filename conventions can be found at https://docs.wis2box.wis.wmo.int/en/latest/reference/running/data-pipeline-plugins.html#wis2box-data-synop2bufr-synop2bufr

**Comment by maaikelimper** [comment]
The error returned depends of the file-pattern defined in the mapping, in the example I saw for Congo: 
`file-pattern: '^.*\.txt$'`

**Comment by maaikelimper** [comment]
The documentation says "Note that the regex must contain two groups (for 4-digit year and 2-digit month), which are used as part of synop2bufr processing." 

I don't think that is sufficient to explain what "validate_filename_pattern" is expecting.

**Comment by maaikelimper** [comment]
I know it is my ignorance on how groups are defined in regex-patterns , sorry ... 

Perhaps we could improve documentation by giving specific examples of what a valid regex would look like.
And we can add some logic in wis2box-management/wis2box/data/synop2bufr.py  that checks that:
- `filematch` hs 2 groups
- the first group has 4 digits for year
- the second group has 2 digits for month ?
And if not throw an error explaining the issue ?

**Comment by tomkralidis** [comment]
2023-05-02: add try/except to explicitly check for year/month.
