### ISSUE TITLE
Elasticsearch Version Upgrade Problem

### ISSUE THREAD

**Issue by mgiannoni** [wmo-im/wis2box#450]
## Elasticsearch Version Upgrade Problem
Performed an update to our Wis2Box installation and the subsequent Elasticsearch container would not start.
Just a few bread-crumbs here showing a fresh wis2box local repo and the change needed to get it working.

## GIT Log

[wis2box@ip-205-156-8-203 wis2box]$ git log
On branch main
Your branch is up to date with 'origin/main'.
commit 07ca9bf8555bd3cb75309ea5b32507e7b92a5ec2 (HEAD -> main, origin/main, origin/HEAD)
Author: Maaike <[maaike.limper@gmail.com](mailto:maaike.limper@gmail.com)>
Date:   Thu May 11 02:13:43 2023 +0200

## GIT Repo Status

`[wis2box@ip-205-156-8-203 wis2box]$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   docker-compose.yml

no changes added to commit (use "git add" and/or "git commit -a")`

## Diff docker-compose.yml

`[wis2box@ip-205-156-8-203 wis2box]$ git diff`
`diff --git a/docker-compose.yml b/docker-compose.yml`
`index 15185bf..eb54e39 100644`
`--- a/docker-compose.yml`
`+++ b/docker-compose.yml`
`@@ -68,7 +68,7 @@ services:`
`   elasticsearch:`
`     container_name: elasticsearch`
`-    image: [docker.elastic.co/elasticsearch/elasticsearch:8.6.2](http://docker.elastic.co/elasticsearch/elasticsearch:8.6.2)`
`+    image: [docker.elastic.co/elasticsearch/elasticsearch:7.16.2](http://docker.elastic.co/elasticsearch/elasticsearch:7.16.2)`
`     restart: always`
`     environment:`
`       - discovery.type=single-node`
`[wis2box@ip-205-156-8-203 wis2box]$`

``

## Elasticsearch Error

elasticsearch  | {"@timestamp":"2023-05-18T15:10:23.820Z", "log.level":"ERROR", "message":
"fatal exception while booting Elasticsearch", "ecs.version": "1.2.0","[service.name](http://service.name/)":"ES_ECS",
"event.dataset":"elasticsearch.server","[process.thread.name](http://process.thread.name/)":"main","log.logger":"org.elasticsearch.bootstrap.Elasticsearch"
,"[elasticsearch.node.name](http://elasticsearch.node.name/)":"elasticsearch-01","[elasticsearch.cluster.name](http://elasticsearch.cluster.name/)":"es-wis2box","error.type":"java.lang.IllegalStateException",
"error.message":"cannot upgrade a node from version [7.16.2] directly to version [8.6.2], upgrade to version [7.17.0] first.",
**"error.stack_trace":"java.lang.IllegalStateException: cannot upgrade a node from version [7.16.2] directly to version [8.6.2], upgrade to version [7.17.0] first.\n\t**
at org.elasticsearch.server@8.6.2/org.elasticsearch.env.NodeMetadata.verifyUpgradeToCurrentVersion(NodeMetadata.java:122)\n\t
at org.elasticsearch.server@8.6.2/org.elasticsearch.env.NodeEnvironment.checkForIndexCompatibility(NodeEnvironment.java:514)\n\t
at org.elasticsearch.server@8.6.2/org.elasticsearch.env.NodeEnvironment.upgradeLegacyNodeFolders(NodeEnvironment.java:408)\n\t
at org.elasticsearch.server@8.6.2/org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:301)\n\t
at org.elasticsearch.server@8.6.2/org.elasticsearch.node.Node.<init>(Node.java:478)\n\t
at org.elasticsearch.server@8.6.2/org.elasticsearch.node.Node.<init>(Node.java:322)\n\t
at org.elasticsearch.server@8.6.2/org.elasticsearch.bootstrap.Elasticsearch$2.<init>(Elasticsearch.java:214)\n\t
at org.elasticsearch.server@8.6.2/org.elasticsearch.bootstrap.Elasticsearch.initPhase3(Elasticsearch.java:214)\n\t
at org.elasticsearch.server@8.6.2/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)\n"}
elasticsearch  | ERROR: Elasticsearch did not exit normally - check the logs at /usr/share/elasticsearch/logs/es-wis2box.log
elasticsearch  |
elasticsearch  | ERROR: Elasticsearch exited unexpectedly

**Comment by mgiannoni** [comment]
## Resolved -kinda-

### WIS2BOX API Needs ES 8

`wis2box-api  | Trying to generate OpenAPI document`
`wis2box-api  | only ES 8+ supported`
`wis2box-api  | Traceback (most recent call last):`

### Solution

Edit **docker-compose.yml** and "march" the Elasticsearch container version to **7.17.0** then up to **8.6.2**.  A workflow not  suitable to a new user.
