### ISSUE TITLE
wis2box metadata discovery unpublish throws error

### ISSUE THREAD

**Issue by maaikelimper** [wmo-im/wis2box#538]
On a fresh install, I run the command :
`wis2box metadata discovery publish /data/wis2box/metadata/discovery/metadata-synop.yml`
and verify publish was successful

then I try to unpublish with the command:
`wis2box metadata discovery unpublish /data/wis2box/metadata/discovery/metadata-synop.yml`

And I get an error from elastic 404 not found

See full output below

```
[root@ea5995904562:/home/wis2box# wis2box metadata discovery publish /data/wis2box/metadata/discovery/metadata-synop.yml
Publishing discovery metadata from /data/wis2box/metadata/discovery/metadata-synop.yml
Done
root@ea5995904562:/home/wis2box# wis2box metadata discovery unpublish /data/wis2box/metadata/discovery/metadata-synop.yml
Unpublishing discovery metadata /data/wis2box/metadata/discovery/metadata-synop.yml
[2023-10-04T18:09:17Z] {/app/wis2box/api/backend/elastic.py:306} ERROR - Item deletion failed: NotFoundError(404, "{'_index': 'discovery-metadata', '_id': '/data/wis2box/metadata/discovery/metadata-synop.yml', '_version': 1, 'result': 'not_found', '_shards': {'total': 1, 'successful': 1, 'failed': 0}, '_seq_no': 1, '_primary_term': 2}")
Traceback (most recent call last):
  File "/app/wis2box/api/backend/elastic.py", line 303, in delete_collection_item
    _ = self.conn.delete(index=collection_id, id=item_id)
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
    return api(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/_sync/client/__init__.py", line 1105, in delete
    return self.perform_request(  # type: ignore[return-value]
  File "/usr/local/lib/python3.8/dist-packages/elasticsearch/_sync/client/_base.py", line 320, in perform_request
    raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
elasticsearch.NotFoundError: NotFoundError(404, "{'_index': 'discovery-metadata', '_id': '/data/wis2box/metadata/discovery/metadata-synop.yml', '_version': 1, 'result': 'not_found', '_shards': {'total': 1, 'successful': 1, 'failed': 0}, '_seq_no': 1, '_primary_term': 2}")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/wis2box", line 11, in <module>
    load_entry_point('wis2box', 'console_scripts', 'wis2box')()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/wis2box/metadata/discovery.py", line 237, in unpublish
    delete_collection_item('discovery-metadata', identifier)
  File "/app/wis2box/api/__init__.py", line 137, in delete_collection_item
    backend.delete_collection_item(collection_id, item_id)
  File "/app/wis2box/api/backend/elastic.py", line 307, in delete_collection_item
    raise RuntimeError(msg)
RuntimeError: Item deletion failed: NotFoundError(404, "{'_index': 'discovery-metadata', '_id': '/data/wis2box/metadata/discovery/metadata-synop.yml', '_version': 1, 'result': 'not_found', '_shards': {'total': 1, 'successful': 1, 'failed': 0}, '_seq_no': 1, '_primary_term': 2}")]([url](url))
```

**Comment by maaikelimper** [comment]
incorrrect use of metadata discovery unpublish

The correct way to use this command is provide an identifier

`/home/wis2box# wis2box metadata discovery unpublish urn:x-wmo:md:rou:test:surface-based-observations.synop
Unpublishing discovery metadata urn:x-wmo:md:rou:test:surface-based-observations.synop
root@ea5995904562:/home/wis2box#
`

**Comment by webb-ben** [comment]
Note this used to use the Topic Hierarchy from `cli_helpers.py`. As Topic Hierarchies and Discovery Metadata ID's are formalized, I suggest implementing checks to better inform the error.
